// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administration.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the Administration module

	/**
	* If enabled (default: false), the migration microflow 'MendixSSO_MigrateUsersToAccount' is executed after start-up. This constant is used and set by Mendix Studio to perform automatic migration when necessary.
	* 
	* Do not enable this constant manually. For projects using Mendix Studio Pro, make sure to read the instructions in the microflow carefully. If migration is required, execute the migration microflow manually.
	*/
	public static boolean getEnableMendixSSOUserMigration()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("Administration.EnableMendixSSOUserMigration");
	}
}