// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package lets_travel.proxies;

public class cities
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject citiesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Lets_Travel.cities";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Choosecities("Choosecities"),
		cities_Tourist("Lets_Travel.cities_Tourist");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public cities(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected cities(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject citiesMendixObject)
	{
		if (citiesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, citiesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.citiesMendixObject = citiesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'cities.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static lets_travel.proxies.cities initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return lets_travel.proxies.cities.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static lets_travel.proxies.cities initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new lets_travel.proxies.cities(context, mendixObject);
	}

	public static lets_travel.proxies.cities load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return lets_travel.proxies.cities.initialize(context, mendixObject);
	}

	public static java.util.List<lets_travel.proxies.cities> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> lets_travel.proxies.cities.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Choosecities
	 */
	public final java.lang.String getChoosecities()
	{
		return getChoosecities(getContext());
	}

	/**
	 * @param context
	 * @return value of Choosecities
	 */
	public final java.lang.String getChoosecities(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Choosecities.toString());
	}

	/**
	 * Set value of Choosecities
	 * @param choosecities
	 */
	public final void setChoosecities(java.lang.String choosecities)
	{
		setChoosecities(getContext(), choosecities);
	}

	/**
	 * Set value of Choosecities
	 * @param context
	 * @param choosecities
	 */
	public final void setChoosecities(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String choosecities)
	{
		getMendixObject().setValue(context, MemberNames.Choosecities.toString(), choosecities);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of cities_Tourist
	 */
	public final lets_travel.proxies.Tourist getcities_Tourist() throws com.mendix.core.CoreException
	{
		return getcities_Tourist(getContext());
	}

	/**
	 * @param context
	 * @return value of cities_Tourist
	 * @throws com.mendix.core.CoreException
	 */
	public final lets_travel.proxies.Tourist getcities_Tourist(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		lets_travel.proxies.Tourist result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.cities_Tourist.toString());
		if (identifier != null) {
			result = lets_travel.proxies.Tourist.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of cities_Tourist
	 * @param cities_tourist
	 */
	public final void setcities_Tourist(lets_travel.proxies.Tourist cities_tourist)
	{
		setcities_Tourist(getContext(), cities_tourist);
	}

	/**
	 * Set value of cities_Tourist
	 * @param context
	 * @param cities_tourist
	 */
	public final void setcities_Tourist(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.Tourist cities_tourist)
	{
		if (cities_tourist == null) {
			getMendixObject().setValue(context, MemberNames.cities_Tourist.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.cities_Tourist.toString(), cities_tourist.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return citiesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final lets_travel.proxies.cities that = (lets_travel.proxies.cities) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
