// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package lets_travel.proxies;

public class EmailHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject emailHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Lets_Travel.EmailHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Username("Username"),
		Link("Link"),
		State("State"),
		OTP("OTP"),
		ArrivalDate("ArrivalDate"),
		ReturnDate("ReturnDate"),
		NoOfTravellers("NoOfTravellers"),
		TouristPhonenumber("TouristPhonenumber"),
		guidename("guidename"),
		touristname("touristname"),
		EmailContent("EmailContent"),
		To("To");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmailHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmailHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject emailHelperMendixObject)
	{
		if (emailHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, emailHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.emailHelperMendixObject = emailHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EmailHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static lets_travel.proxies.EmailHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return lets_travel.proxies.EmailHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static lets_travel.proxies.EmailHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new lets_travel.proxies.EmailHelper(context, mendixObject);
	}

	public static lets_travel.proxies.EmailHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return lets_travel.proxies.EmailHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Username
	 */
	public final java.lang.String getUsername()
	{
		return getUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of Username
	 */
	public final java.lang.String getUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Username.toString());
	}

	/**
	 * Set value of Username
	 * @param username
	 */
	public final void setUsername(java.lang.String username)
	{
		setUsername(getContext(), username);
	}

	/**
	 * Set value of Username
	 * @param context
	 * @param username
	 */
	public final void setUsername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.Username.toString(), username);
	}

	/**
	 * @return value of Link
	 */
	public final java.lang.String getLink()
	{
		return getLink(getContext());
	}

	/**
	 * @param context
	 * @return value of Link
	 */
	public final java.lang.String getLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Link.toString());
	}

	/**
	 * Set value of Link
	 * @param link
	 */
	public final void setLink(java.lang.String link)
	{
		setLink(getContext(), link);
	}

	/**
	 * Set value of Link
	 * @param context
	 * @param link
	 */
	public final void setLink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String link)
	{
		getMendixObject().setValue(context, MemberNames.Link.toString(), link);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @return value of OTP
	 */
	public final java.lang.Integer getOTP()
	{
		return getOTP(getContext());
	}

	/**
	 * @param context
	 * @return value of OTP
	 */
	public final java.lang.Integer getOTP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OTP.toString());
	}

	/**
	 * Set value of OTP
	 * @param otp
	 */
	public final void setOTP(java.lang.Integer otp)
	{
		setOTP(getContext(), otp);
	}

	/**
	 * Set value of OTP
	 * @param context
	 * @param otp
	 */
	public final void setOTP(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer otp)
	{
		getMendixObject().setValue(context, MemberNames.OTP.toString(), otp);
	}

	/**
	 * @return value of ArrivalDate
	 */
	public final java.util.Date getArrivalDate()
	{
		return getArrivalDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ArrivalDate
	 */
	public final java.util.Date getArrivalDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ArrivalDate.toString());
	}

	/**
	 * Set value of ArrivalDate
	 * @param arrivaldate
	 */
	public final void setArrivalDate(java.util.Date arrivaldate)
	{
		setArrivalDate(getContext(), arrivaldate);
	}

	/**
	 * Set value of ArrivalDate
	 * @param context
	 * @param arrivaldate
	 */
	public final void setArrivalDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date arrivaldate)
	{
		getMendixObject().setValue(context, MemberNames.ArrivalDate.toString(), arrivaldate);
	}

	/**
	 * @return value of ReturnDate
	 */
	public final java.util.Date getReturnDate()
	{
		return getReturnDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ReturnDate
	 */
	public final java.util.Date getReturnDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ReturnDate.toString());
	}

	/**
	 * Set value of ReturnDate
	 * @param returndate
	 */
	public final void setReturnDate(java.util.Date returndate)
	{
		setReturnDate(getContext(), returndate);
	}

	/**
	 * Set value of ReturnDate
	 * @param context
	 * @param returndate
	 */
	public final void setReturnDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date returndate)
	{
		getMendixObject().setValue(context, MemberNames.ReturnDate.toString(), returndate);
	}

	/**
	 * @return value of NoOfTravellers
	 */
	public final java.lang.Integer getNoOfTravellers()
	{
		return getNoOfTravellers(getContext());
	}

	/**
	 * @param context
	 * @return value of NoOfTravellers
	 */
	public final java.lang.Integer getNoOfTravellers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NoOfTravellers.toString());
	}

	/**
	 * Set value of NoOfTravellers
	 * @param nooftravellers
	 */
	public final void setNoOfTravellers(java.lang.Integer nooftravellers)
	{
		setNoOfTravellers(getContext(), nooftravellers);
	}

	/**
	 * Set value of NoOfTravellers
	 * @param context
	 * @param nooftravellers
	 */
	public final void setNoOfTravellers(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nooftravellers)
	{
		getMendixObject().setValue(context, MemberNames.NoOfTravellers.toString(), nooftravellers);
	}

	/**
	 * @return value of TouristPhonenumber
	 */
	public final java.lang.String getTouristPhonenumber()
	{
		return getTouristPhonenumber(getContext());
	}

	/**
	 * @param context
	 * @return value of TouristPhonenumber
	 */
	public final java.lang.String getTouristPhonenumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TouristPhonenumber.toString());
	}

	/**
	 * Set value of TouristPhonenumber
	 * @param touristphonenumber
	 */
	public final void setTouristPhonenumber(java.lang.String touristphonenumber)
	{
		setTouristPhonenumber(getContext(), touristphonenumber);
	}

	/**
	 * Set value of TouristPhonenumber
	 * @param context
	 * @param touristphonenumber
	 */
	public final void setTouristPhonenumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String touristphonenumber)
	{
		getMendixObject().setValue(context, MemberNames.TouristPhonenumber.toString(), touristphonenumber);
	}

	/**
	 * @return value of guidename
	 */
	public final java.lang.String getguidename()
	{
		return getguidename(getContext());
	}

	/**
	 * @param context
	 * @return value of guidename
	 */
	public final java.lang.String getguidename(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.guidename.toString());
	}

	/**
	 * Set value of guidename
	 * @param guidename
	 */
	public final void setguidename(java.lang.String guidename)
	{
		setguidename(getContext(), guidename);
	}

	/**
	 * Set value of guidename
	 * @param context
	 * @param guidename
	 */
	public final void setguidename(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String guidename)
	{
		getMendixObject().setValue(context, MemberNames.guidename.toString(), guidename);
	}

	/**
	 * @return value of touristname
	 */
	public final java.lang.String gettouristname()
	{
		return gettouristname(getContext());
	}

	/**
	 * @param context
	 * @return value of touristname
	 */
	public final java.lang.String gettouristname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.touristname.toString());
	}

	/**
	 * Set value of touristname
	 * @param touristname
	 */
	public final void settouristname(java.lang.String touristname)
	{
		settouristname(getContext(), touristname);
	}

	/**
	 * Set value of touristname
	 * @param context
	 * @param touristname
	 */
	public final void settouristname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String touristname)
	{
		getMendixObject().setValue(context, MemberNames.touristname.toString(), touristname);
	}

	/**
	 * @return value of EmailContent
	 */
	public final java.lang.String getEmailContent()
	{
		return getEmailContent(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailContent
	 */
	public final java.lang.String getEmailContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailContent.toString());
	}

	/**
	 * Set value of EmailContent
	 * @param emailcontent
	 */
	public final void setEmailContent(java.lang.String emailcontent)
	{
		setEmailContent(getContext(), emailcontent);
	}

	/**
	 * Set value of EmailContent
	 * @param context
	 * @param emailcontent
	 */
	public final void setEmailContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailcontent)
	{
		getMendixObject().setValue(context, MemberNames.EmailContent.toString(), emailcontent);
	}

	/**
	 * @return value of To
	 */
	public final java.lang.String getTo()
	{
		return getTo(getContext());
	}

	/**
	 * @param context
	 * @return value of To
	 */
	public final java.lang.String getTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.To.toString());
	}

	/**
	 * Set value of To
	 * @param to
	 */
	public final void setTo(java.lang.String to)
	{
		setTo(getContext(), to);
	}

	/**
	 * Set value of To
	 * @param context
	 * @param to
	 */
	public final void setTo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String to)
	{
		getMendixObject().setValue(context, MemberNames.To.toString(), to);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return emailHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final lets_travel.proxies.EmailHelper that = (lets_travel.proxies.EmailHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
