// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package lets_travel.proxies;

public class Guide extends administration.proxies.Account
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Lets_Travel.Guide";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Address("Address"),
		Phone("Phone"),
		Company("Company"),
		CompanyRegistration("CompanyRegistration"),
		TaxIdNumber("TaxIdNumber"),
		TourGuideLicence("TourGuideLicence"),
		State("State"),
		Languages("Languages"),
		BudgetRange("BudgetRange"),
		LicenceFile("LicenceFile"),
		Number("Number"),
		OTP("OTP"),
		ValidateOtp("ValidateOtp"),
		FullName("FullName"),
		Email("Email"),
		IsLocalUser("IsLocalUser"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		BlockedSince("BlockedSince"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		GuideProfilePicture_Guide("Lets_Travel.GuideProfilePicture_Guide"),
		Guide_cities("Lets_Travel.Guide_cities"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Guide(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Guide(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject guideMendixObject)
	{
		super(context, guideMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, guideMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'Guide.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static lets_travel.proxies.Guide initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return lets_travel.proxies.Guide.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static lets_travel.proxies.Guide initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new lets_travel.proxies.Guide(context, mendixObject);
	}

	public static lets_travel.proxies.Guide load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return lets_travel.proxies.Guide.initialize(context, mendixObject);
	}

	public static java.util.List<lets_travel.proxies.Guide> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> lets_travel.proxies.Guide.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * @return value of Phone
	 */
	public final java.lang.String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final java.lang.String getPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(java.lang.String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * @return value of Company
	 */
	public final java.lang.Boolean getCompany()
	{
		return getCompany(getContext());
	}

	/**
	 * @param context
	 * @return value of Company
	 */
	public final java.lang.Boolean getCompany(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Company.toString());
	}

	/**
	 * Set value of Company
	 * @param company
	 */
	public final void setCompany(java.lang.Boolean company)
	{
		setCompany(getContext(), company);
	}

	/**
	 * Set value of Company
	 * @param context
	 * @param company
	 */
	public final void setCompany(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean company)
	{
		getMendixObject().setValue(context, MemberNames.Company.toString(), company);
	}

	/**
	 * @return value of CompanyRegistration
	 */
	public final java.lang.String getCompanyRegistration()
	{
		return getCompanyRegistration(getContext());
	}

	/**
	 * @param context
	 * @return value of CompanyRegistration
	 */
	public final java.lang.String getCompanyRegistration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CompanyRegistration.toString());
	}

	/**
	 * Set value of CompanyRegistration
	 * @param companyregistration
	 */
	public final void setCompanyRegistration(java.lang.String companyregistration)
	{
		setCompanyRegistration(getContext(), companyregistration);
	}

	/**
	 * Set value of CompanyRegistration
	 * @param context
	 * @param companyregistration
	 */
	public final void setCompanyRegistration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String companyregistration)
	{
		getMendixObject().setValue(context, MemberNames.CompanyRegistration.toString(), companyregistration);
	}

	/**
	 * @return value of TaxIdNumber
	 */
	public final java.lang.String getTaxIdNumber()
	{
		return getTaxIdNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of TaxIdNumber
	 */
	public final java.lang.String getTaxIdNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TaxIdNumber.toString());
	}

	/**
	 * Set value of TaxIdNumber
	 * @param taxidnumber
	 */
	public final void setTaxIdNumber(java.lang.String taxidnumber)
	{
		setTaxIdNumber(getContext(), taxidnumber);
	}

	/**
	 * Set value of TaxIdNumber
	 * @param context
	 * @param taxidnumber
	 */
	public final void setTaxIdNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String taxidnumber)
	{
		getMendixObject().setValue(context, MemberNames.TaxIdNumber.toString(), taxidnumber);
	}

	/**
	 * @return value of TourGuideLicence
	 */
	public final java.lang.String getTourGuideLicence()
	{
		return getTourGuideLicence(getContext());
	}

	/**
	 * @param context
	 * @return value of TourGuideLicence
	 */
	public final java.lang.String getTourGuideLicence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TourGuideLicence.toString());
	}

	/**
	 * Set value of TourGuideLicence
	 * @param tourguidelicence
	 */
	public final void setTourGuideLicence(java.lang.String tourguidelicence)
	{
		setTourGuideLicence(getContext(), tourguidelicence);
	}

	/**
	 * Set value of TourGuideLicence
	 * @param context
	 * @param tourguidelicence
	 */
	public final void setTourGuideLicence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tourguidelicence)
	{
		getMendixObject().setValue(context, MemberNames.TourGuideLicence.toString(), tourguidelicence);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * Set value of Languages
	 * @param languages
	 */
	public final lets_travel.proxies.Languages getLanguages()
	{
		return getLanguages(getContext());
	}

	/**
	 * @param context
	 * @return value of Languages
	 */
	public final lets_travel.proxies.Languages getLanguages(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Languages.toString());
		if (obj == null) {
			return null;
		}
		return lets_travel.proxies.Languages.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Languages
	 * @param languages
	 */
	public final void setLanguages(lets_travel.proxies.Languages languages)
	{
		setLanguages(getContext(), languages);
	}

	/**
	 * Set value of Languages
	 * @param context
	 * @param languages
	 */
	public final void setLanguages(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.Languages languages)
	{
		if (languages != null) {
			getMendixObject().setValue(context, MemberNames.Languages.toString(), languages.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Languages.toString(), null);
		}
	}

	/**
	 * @return value of BudgetRange
	 */
	public final java.lang.Integer getBudgetRange()
	{
		return getBudgetRange(getContext());
	}

	/**
	 * @param context
	 * @return value of BudgetRange
	 */
	public final java.lang.Integer getBudgetRange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.BudgetRange.toString());
	}

	/**
	 * Set value of BudgetRange
	 * @param budgetrange
	 */
	public final void setBudgetRange(java.lang.Integer budgetrange)
	{
		setBudgetRange(getContext(), budgetrange);
	}

	/**
	 * Set value of BudgetRange
	 * @param context
	 * @param budgetrange
	 */
	public final void setBudgetRange(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer budgetrange)
	{
		getMendixObject().setValue(context, MemberNames.BudgetRange.toString(), budgetrange);
	}

	/**
	 * @return value of LicenceFile
	 */
	public final java.lang.String getLicenceFile()
	{
		return getLicenceFile(getContext());
	}

	/**
	 * @param context
	 * @return value of LicenceFile
	 */
	public final java.lang.String getLicenceFile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LicenceFile.toString());
	}

	/**
	 * Set value of LicenceFile
	 * @param licencefile
	 */
	public final void setLicenceFile(java.lang.String licencefile)
	{
		setLicenceFile(getContext(), licencefile);
	}

	/**
	 * Set value of LicenceFile
	 * @param context
	 * @param licencefile
	 */
	public final void setLicenceFile(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String licencefile)
	{
		getMendixObject().setValue(context, MemberNames.LicenceFile.toString(), licencefile);
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.Long getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Long getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Long number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of OTP
	 */
	public final java.lang.Integer getOTP()
	{
		return getOTP(getContext());
	}

	/**
	 * @param context
	 * @return value of OTP
	 */
	public final java.lang.Integer getOTP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OTP.toString());
	}

	/**
	 * Set value of OTP
	 * @param otp
	 */
	public final void setOTP(java.lang.Integer otp)
	{
		setOTP(getContext(), otp);
	}

	/**
	 * Set value of OTP
	 * @param context
	 * @param otp
	 */
	public final void setOTP(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer otp)
	{
		getMendixObject().setValue(context, MemberNames.OTP.toString(), otp);
	}

	/**
	 * @return value of ValidateOtp
	 */
	public final java.lang.Integer getValidateOtp()
	{
		return getValidateOtp(getContext());
	}

	/**
	 * @param context
	 * @return value of ValidateOtp
	 */
	public final java.lang.Integer getValidateOtp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ValidateOtp.toString());
	}

	/**
	 * Set value of ValidateOtp
	 * @param validateotp
	 */
	public final void setValidateOtp(java.lang.Integer validateotp)
	{
		setValidateOtp(getContext(), validateotp);
	}

	/**
	 * Set value of ValidateOtp
	 * @param context
	 * @param validateotp
	 */
	public final void setValidateOtp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer validateotp)
	{
		getMendixObject().setValue(context, MemberNames.ValidateOtp.toString(), validateotp);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GuideProfilePicture_Guide
	 */
	public final lets_travel.proxies.GuideProfilePicture getGuideProfilePicture_Guide() throws com.mendix.core.CoreException
	{
		return getGuideProfilePicture_Guide(getContext());
	}

	/**
	 * @param context
	 * @return value of GuideProfilePicture_Guide
	 * @throws com.mendix.core.CoreException
	 */
	public final lets_travel.proxies.GuideProfilePicture getGuideProfilePicture_Guide(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		lets_travel.proxies.GuideProfilePicture result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GuideProfilePicture_Guide.toString());
		if (identifier != null) {
			result = lets_travel.proxies.GuideProfilePicture.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of GuideProfilePicture_Guide
	 * @param guideprofilepicture_guide
	 */
	public final void setGuideProfilePicture_Guide(lets_travel.proxies.GuideProfilePicture guideprofilepicture_guide)
	{
		setGuideProfilePicture_Guide(getContext(), guideprofilepicture_guide);
	}

	/**
	 * Set value of GuideProfilePicture_Guide
	 * @param context
	 * @param guideprofilepicture_guide
	 */
	public final void setGuideProfilePicture_Guide(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.GuideProfilePicture guideprofilepicture_guide)
	{
		if (guideprofilepicture_guide == null) {
			getMendixObject().setValue(context, MemberNames.GuideProfilePicture_Guide.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.GuideProfilePicture_Guide.toString(), guideprofilepicture_guide.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Guide_cities
	 */
	public final lets_travel.proxies.cities getGuide_cities() throws com.mendix.core.CoreException
	{
		return getGuide_cities(getContext());
	}

	/**
	 * @param context
	 * @return value of Guide_cities
	 * @throws com.mendix.core.CoreException
	 */
	public final lets_travel.proxies.cities getGuide_cities(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		lets_travel.proxies.cities result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Guide_cities.toString());
		if (identifier != null) {
			result = lets_travel.proxies.cities.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Guide_cities
	 * @param guide_cities
	 */
	public final void setGuide_cities(lets_travel.proxies.cities guide_cities)
	{
		setGuide_cities(getContext(), guide_cities);
	}

	/**
	 * Set value of Guide_cities
	 * @param context
	 * @param guide_cities
	 */
	public final void setGuide_cities(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.cities guide_cities)
	{
		if (guide_cities == null) {
			getMendixObject().setValue(context, MemberNames.Guide_cities.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Guide_cities.toString(), guide_cities.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final lets_travel.proxies.Guide that = (lets_travel.proxies.Guide) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
