// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package lets_travel.proxies;

public class Guide_npe
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject guide_npeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Lets_Travel.Guide_npe";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Address("Address"),
		Phone("Phone"),
		Email("Email"),
		Password("Password"),
		ConfirmPassword("ConfirmPassword"),
		Company("Company"),
		CompanyRegistration("CompanyRegistration"),
		TaxIdNumber("TaxIdNumber"),
		TourGuideLicence("TourGuideLicence"),
		Countries("Countries"),
		State("State"),
		Languages("Languages"),
		BudgetRange("BudgetRange"),
		LicenceFile("LicenceFile");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Guide_npe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Guide_npe(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject guide_npeMendixObject)
	{
		if (guide_npeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, guide_npeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.guide_npeMendixObject = guide_npeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Guide_npe.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static lets_travel.proxies.Guide_npe initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return lets_travel.proxies.Guide_npe.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static lets_travel.proxies.Guide_npe initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new lets_travel.proxies.Guide_npe(context, mendixObject);
	}

	public static lets_travel.proxies.Guide_npe load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return lets_travel.proxies.Guide_npe.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * @return value of Phone
	 */
	public final java.lang.String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final java.lang.String getPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(java.lang.String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of ConfirmPassword
	 */
	public final java.lang.String getConfirmPassword()
	{
		return getConfirmPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfirmPassword
	 */
	public final java.lang.String getConfirmPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConfirmPassword.toString());
	}

	/**
	 * Set value of ConfirmPassword
	 * @param confirmpassword
	 */
	public final void setConfirmPassword(java.lang.String confirmpassword)
	{
		setConfirmPassword(getContext(), confirmpassword);
	}

	/**
	 * Set value of ConfirmPassword
	 * @param context
	 * @param confirmpassword
	 */
	public final void setConfirmPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String confirmpassword)
	{
		getMendixObject().setValue(context, MemberNames.ConfirmPassword.toString(), confirmpassword);
	}

	/**
	 * @return value of Company
	 */
	public final java.lang.Boolean getCompany()
	{
		return getCompany(getContext());
	}

	/**
	 * @param context
	 * @return value of Company
	 */
	public final java.lang.Boolean getCompany(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Company.toString());
	}

	/**
	 * Set value of Company
	 * @param company
	 */
	public final void setCompany(java.lang.Boolean company)
	{
		setCompany(getContext(), company);
	}

	/**
	 * Set value of Company
	 * @param context
	 * @param company
	 */
	public final void setCompany(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean company)
	{
		getMendixObject().setValue(context, MemberNames.Company.toString(), company);
	}

	/**
	 * @return value of CompanyRegistration
	 */
	public final java.lang.String getCompanyRegistration()
	{
		return getCompanyRegistration(getContext());
	}

	/**
	 * @param context
	 * @return value of CompanyRegistration
	 */
	public final java.lang.String getCompanyRegistration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CompanyRegistration.toString());
	}

	/**
	 * Set value of CompanyRegistration
	 * @param companyregistration
	 */
	public final void setCompanyRegistration(java.lang.String companyregistration)
	{
		setCompanyRegistration(getContext(), companyregistration);
	}

	/**
	 * Set value of CompanyRegistration
	 * @param context
	 * @param companyregistration
	 */
	public final void setCompanyRegistration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String companyregistration)
	{
		getMendixObject().setValue(context, MemberNames.CompanyRegistration.toString(), companyregistration);
	}

	/**
	 * @return value of TaxIdNumber
	 */
	public final java.lang.String getTaxIdNumber()
	{
		return getTaxIdNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of TaxIdNumber
	 */
	public final java.lang.String getTaxIdNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TaxIdNumber.toString());
	}

	/**
	 * Set value of TaxIdNumber
	 * @param taxidnumber
	 */
	public final void setTaxIdNumber(java.lang.String taxidnumber)
	{
		setTaxIdNumber(getContext(), taxidnumber);
	}

	/**
	 * Set value of TaxIdNumber
	 * @param context
	 * @param taxidnumber
	 */
	public final void setTaxIdNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String taxidnumber)
	{
		getMendixObject().setValue(context, MemberNames.TaxIdNumber.toString(), taxidnumber);
	}

	/**
	 * @return value of TourGuideLicence
	 */
	public final java.lang.String getTourGuideLicence()
	{
		return getTourGuideLicence(getContext());
	}

	/**
	 * @param context
	 * @return value of TourGuideLicence
	 */
	public final java.lang.String getTourGuideLicence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TourGuideLicence.toString());
	}

	/**
	 * Set value of TourGuideLicence
	 * @param tourguidelicence
	 */
	public final void setTourGuideLicence(java.lang.String tourguidelicence)
	{
		setTourGuideLicence(getContext(), tourguidelicence);
	}

	/**
	 * Set value of TourGuideLicence
	 * @param context
	 * @param tourguidelicence
	 */
	public final void setTourGuideLicence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tourguidelicence)
	{
		getMendixObject().setValue(context, MemberNames.TourGuideLicence.toString(), tourguidelicence);
	}

	/**
	 * Set value of Countries
	 * @param countries
	 */
	public final lets_travel.proxies.Countries getCountries()
	{
		return getCountries(getContext());
	}

	/**
	 * @param context
	 * @return value of Countries
	 */
	public final lets_travel.proxies.Countries getCountries(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Countries.toString());
		if (obj == null) {
			return null;
		}
		return lets_travel.proxies.Countries.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Countries
	 * @param countries
	 */
	public final void setCountries(lets_travel.proxies.Countries countries)
	{
		setCountries(getContext(), countries);
	}

	/**
	 * Set value of Countries
	 * @param context
	 * @param countries
	 */
	public final void setCountries(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.Countries countries)
	{
		if (countries != null) {
			getMendixObject().setValue(context, MemberNames.Countries.toString(), countries.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Countries.toString(), null);
		}
	}

	/**
	 * @return value of State
	 */
	public final java.lang.String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * Set value of Languages
	 * @param languages
	 */
	public final lets_travel.proxies.Languages getLanguages()
	{
		return getLanguages(getContext());
	}

	/**
	 * @param context
	 * @return value of Languages
	 */
	public final lets_travel.proxies.Languages getLanguages(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Languages.toString());
		if (obj == null) {
			return null;
		}
		return lets_travel.proxies.Languages.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Languages
	 * @param languages
	 */
	public final void setLanguages(lets_travel.proxies.Languages languages)
	{
		setLanguages(getContext(), languages);
	}

	/**
	 * Set value of Languages
	 * @param context
	 * @param languages
	 */
	public final void setLanguages(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.Languages languages)
	{
		if (languages != null) {
			getMendixObject().setValue(context, MemberNames.Languages.toString(), languages.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Languages.toString(), null);
		}
	}

	/**
	 * @return value of BudgetRange
	 */
	public final java.lang.Integer getBudgetRange()
	{
		return getBudgetRange(getContext());
	}

	/**
	 * @param context
	 * @return value of BudgetRange
	 */
	public final java.lang.Integer getBudgetRange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.BudgetRange.toString());
	}

	/**
	 * Set value of BudgetRange
	 * @param budgetrange
	 */
	public final void setBudgetRange(java.lang.Integer budgetrange)
	{
		setBudgetRange(getContext(), budgetrange);
	}

	/**
	 * Set value of BudgetRange
	 * @param context
	 * @param budgetrange
	 */
	public final void setBudgetRange(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer budgetrange)
	{
		getMendixObject().setValue(context, MemberNames.BudgetRange.toString(), budgetrange);
	}

	/**
	 * @return value of LicenceFile
	 */
	public final java.lang.String getLicenceFile()
	{
		return getLicenceFile(getContext());
	}

	/**
	 * @param context
	 * @return value of LicenceFile
	 */
	public final java.lang.String getLicenceFile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LicenceFile.toString());
	}

	/**
	 * Set value of LicenceFile
	 * @param licencefile
	 */
	public final void setLicenceFile(java.lang.String licencefile)
	{
		setLicenceFile(getContext(), licencefile);
	}

	/**
	 * Set value of LicenceFile
	 * @param context
	 * @param licencefile
	 */
	public final void setLicenceFile(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String licencefile)
	{
		getMendixObject().setValue(context, MemberNames.LicenceFile.toString(), licencefile);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return guide_npeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final lets_travel.proxies.Guide_npe that = (lets_travel.proxies.Guide_npe) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
