// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package lets_travel.proxies;

public class GuideProfilePicture extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Lets_Travel.GuideProfilePicture";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		GuideProfilePicture_Guide("Lets_Travel.GuideProfilePicture_Guide");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GuideProfilePicture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GuideProfilePicture(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject guideProfilePictureMendixObject)
	{
		super(context, guideProfilePictureMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, guideProfilePictureMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'GuideProfilePicture.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static lets_travel.proxies.GuideProfilePicture initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return lets_travel.proxies.GuideProfilePicture.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static lets_travel.proxies.GuideProfilePicture initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new lets_travel.proxies.GuideProfilePicture(context, mendixObject);
	}

	public static lets_travel.proxies.GuideProfilePicture load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return lets_travel.proxies.GuideProfilePicture.initialize(context, mendixObject);
	}

	public static java.util.List<lets_travel.proxies.GuideProfilePicture> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> lets_travel.proxies.GuideProfilePicture.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GuideProfilePicture_Guide
	 */
	public final lets_travel.proxies.Guide getGuideProfilePicture_Guide() throws com.mendix.core.CoreException
	{
		return getGuideProfilePicture_Guide(getContext());
	}

	/**
	 * @param context
	 * @return value of GuideProfilePicture_Guide
	 * @throws com.mendix.core.CoreException
	 */
	public final lets_travel.proxies.Guide getGuideProfilePicture_Guide(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		lets_travel.proxies.Guide result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GuideProfilePicture_Guide.toString());
		if (identifier != null) {
			result = lets_travel.proxies.Guide.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of GuideProfilePicture_Guide
	 * @param guideprofilepicture_guide
	 */
	public final void setGuideProfilePicture_Guide(lets_travel.proxies.Guide guideprofilepicture_guide)
	{
		setGuideProfilePicture_Guide(getContext(), guideprofilepicture_guide);
	}

	/**
	 * Set value of GuideProfilePicture_Guide
	 * @param context
	 * @param guideprofilepicture_guide
	 */
	public final void setGuideProfilePicture_Guide(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.Guide guideprofilepicture_guide)
	{
		if (guideprofilepicture_guide == null) {
			getMendixObject().setValue(context, MemberNames.GuideProfilePicture_Guide.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.GuideProfilePicture_Guide.toString(), guideprofilepicture_guide.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final lets_travel.proxies.GuideProfilePicture that = (lets_travel.proxies.GuideProfilePicture) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
