// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package lets_travel.proxies;

public class TouristBookingDetails
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject touristBookingDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Lets_Travel.TouristBookingDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ArrivalDate("ArrivalDate"),
		ReturnDate("ReturnDate"),
		NoOfTravellers("NoOfTravellers"),
		SpecialNote("SpecialNote"),
		CreditCardInfo("CreditCardInfo"),
		Phone("Phone"),
		TouristBookingDetails_Guide("Lets_Travel.TouristBookingDetails_Guide"),
		TouristBookingDetails_Tourist("Lets_Travel.TouristBookingDetails_Tourist");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TouristBookingDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TouristBookingDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject touristBookingDetailsMendixObject)
	{
		if (touristBookingDetailsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, touristBookingDetailsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.touristBookingDetailsMendixObject = touristBookingDetailsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TouristBookingDetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static lets_travel.proxies.TouristBookingDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return lets_travel.proxies.TouristBookingDetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static lets_travel.proxies.TouristBookingDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new lets_travel.proxies.TouristBookingDetails(context, mendixObject);
	}

	public static lets_travel.proxies.TouristBookingDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return lets_travel.proxies.TouristBookingDetails.initialize(context, mendixObject);
	}

	public static java.util.List<lets_travel.proxies.TouristBookingDetails> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> lets_travel.proxies.TouristBookingDetails.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ArrivalDate
	 */
	public final java.util.Date getArrivalDate()
	{
		return getArrivalDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ArrivalDate
	 */
	public final java.util.Date getArrivalDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ArrivalDate.toString());
	}

	/**
	 * Set value of ArrivalDate
	 * @param arrivaldate
	 */
	public final void setArrivalDate(java.util.Date arrivaldate)
	{
		setArrivalDate(getContext(), arrivaldate);
	}

	/**
	 * Set value of ArrivalDate
	 * @param context
	 * @param arrivaldate
	 */
	public final void setArrivalDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date arrivaldate)
	{
		getMendixObject().setValue(context, MemberNames.ArrivalDate.toString(), arrivaldate);
	}

	/**
	 * @return value of ReturnDate
	 */
	public final java.util.Date getReturnDate()
	{
		return getReturnDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ReturnDate
	 */
	public final java.util.Date getReturnDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ReturnDate.toString());
	}

	/**
	 * Set value of ReturnDate
	 * @param returndate
	 */
	public final void setReturnDate(java.util.Date returndate)
	{
		setReturnDate(getContext(), returndate);
	}

	/**
	 * Set value of ReturnDate
	 * @param context
	 * @param returndate
	 */
	public final void setReturnDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date returndate)
	{
		getMendixObject().setValue(context, MemberNames.ReturnDate.toString(), returndate);
	}

	/**
	 * @return value of NoOfTravellers
	 */
	public final java.lang.Integer getNoOfTravellers()
	{
		return getNoOfTravellers(getContext());
	}

	/**
	 * @param context
	 * @return value of NoOfTravellers
	 */
	public final java.lang.Integer getNoOfTravellers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NoOfTravellers.toString());
	}

	/**
	 * Set value of NoOfTravellers
	 * @param nooftravellers
	 */
	public final void setNoOfTravellers(java.lang.Integer nooftravellers)
	{
		setNoOfTravellers(getContext(), nooftravellers);
	}

	/**
	 * Set value of NoOfTravellers
	 * @param context
	 * @param nooftravellers
	 */
	public final void setNoOfTravellers(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nooftravellers)
	{
		getMendixObject().setValue(context, MemberNames.NoOfTravellers.toString(), nooftravellers);
	}

	/**
	 * @return value of SpecialNote
	 */
	public final java.lang.String getSpecialNote()
	{
		return getSpecialNote(getContext());
	}

	/**
	 * @param context
	 * @return value of SpecialNote
	 */
	public final java.lang.String getSpecialNote(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SpecialNote.toString());
	}

	/**
	 * Set value of SpecialNote
	 * @param specialnote
	 */
	public final void setSpecialNote(java.lang.String specialnote)
	{
		setSpecialNote(getContext(), specialnote);
	}

	/**
	 * Set value of SpecialNote
	 * @param context
	 * @param specialnote
	 */
	public final void setSpecialNote(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String specialnote)
	{
		getMendixObject().setValue(context, MemberNames.SpecialNote.toString(), specialnote);
	}

	/**
	 * @return value of CreditCardInfo
	 */
	public final java.lang.String getCreditCardInfo()
	{
		return getCreditCardInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of CreditCardInfo
	 */
	public final java.lang.String getCreditCardInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CreditCardInfo.toString());
	}

	/**
	 * Set value of CreditCardInfo
	 * @param creditcardinfo
	 */
	public final void setCreditCardInfo(java.lang.String creditcardinfo)
	{
		setCreditCardInfo(getContext(), creditcardinfo);
	}

	/**
	 * Set value of CreditCardInfo
	 * @param context
	 * @param creditcardinfo
	 */
	public final void setCreditCardInfo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String creditcardinfo)
	{
		getMendixObject().setValue(context, MemberNames.CreditCardInfo.toString(), creditcardinfo);
	}

	/**
	 * @return value of Phone
	 */
	public final java.lang.String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final java.lang.String getPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(java.lang.String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TouristBookingDetails_Guide
	 */
	public final lets_travel.proxies.Guide getTouristBookingDetails_Guide() throws com.mendix.core.CoreException
	{
		return getTouristBookingDetails_Guide(getContext());
	}

	/**
	 * @param context
	 * @return value of TouristBookingDetails_Guide
	 * @throws com.mendix.core.CoreException
	 */
	public final lets_travel.proxies.Guide getTouristBookingDetails_Guide(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		lets_travel.proxies.Guide result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TouristBookingDetails_Guide.toString());
		if (identifier != null) {
			result = lets_travel.proxies.Guide.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TouristBookingDetails_Guide
	 * @param touristbookingdetails_guide
	 */
	public final void setTouristBookingDetails_Guide(lets_travel.proxies.Guide touristbookingdetails_guide)
	{
		setTouristBookingDetails_Guide(getContext(), touristbookingdetails_guide);
	}

	/**
	 * Set value of TouristBookingDetails_Guide
	 * @param context
	 * @param touristbookingdetails_guide
	 */
	public final void setTouristBookingDetails_Guide(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.Guide touristbookingdetails_guide)
	{
		if (touristbookingdetails_guide == null) {
			getMendixObject().setValue(context, MemberNames.TouristBookingDetails_Guide.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TouristBookingDetails_Guide.toString(), touristbookingdetails_guide.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TouristBookingDetails_Tourist
	 */
	public final lets_travel.proxies.Tourist getTouristBookingDetails_Tourist() throws com.mendix.core.CoreException
	{
		return getTouristBookingDetails_Tourist(getContext());
	}

	/**
	 * @param context
	 * @return value of TouristBookingDetails_Tourist
	 * @throws com.mendix.core.CoreException
	 */
	public final lets_travel.proxies.Tourist getTouristBookingDetails_Tourist(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		lets_travel.proxies.Tourist result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TouristBookingDetails_Tourist.toString());
		if (identifier != null) {
			result = lets_travel.proxies.Tourist.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TouristBookingDetails_Tourist
	 * @param touristbookingdetails_tourist
	 */
	public final void setTouristBookingDetails_Tourist(lets_travel.proxies.Tourist touristbookingdetails_tourist)
	{
		setTouristBookingDetails_Tourist(getContext(), touristbookingdetails_tourist);
	}

	/**
	 * Set value of TouristBookingDetails_Tourist
	 * @param context
	 * @param touristbookingdetails_tourist
	 */
	public final void setTouristBookingDetails_Tourist(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.Tourist touristbookingdetails_tourist)
	{
		if (touristbookingdetails_tourist == null) {
			getMendixObject().setValue(context, MemberNames.TouristBookingDetails_Tourist.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TouristBookingDetails_Tourist.toString(), touristbookingdetails_tourist.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return touristBookingDetailsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final lets_travel.proxies.TouristBookingDetails that = (lets_travel.proxies.TouristBookingDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
