// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package lets_travel.proxies;

public class Tourist extends administration.proxies.Account
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Lets_Travel.Tourist";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DOB("DOB"),
		Address("Address"),
		Phone("Phone"),
		State("State"),
		FamilyType("FamilyType"),
		Budget("Budget"),
		states("states"),
		ValidateOtp("ValidateOtp"),
		OTP("OTP"),
		FullName("FullName"),
		Email("Email"),
		IsLocalUser("IsLocalUser"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		BlockedSince("BlockedSince"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		Tourist_Guide("Lets_Travel.Tourist_Guide"),
		TouristProfilePicture_Tourist("Lets_Travel.TouristProfilePicture_Tourist"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Tourist(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Tourist(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject touristMendixObject)
	{
		super(context, touristMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, touristMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'Tourist.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static lets_travel.proxies.Tourist initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return lets_travel.proxies.Tourist.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static lets_travel.proxies.Tourist initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new lets_travel.proxies.Tourist(context, mendixObject);
	}

	public static lets_travel.proxies.Tourist load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return lets_travel.proxies.Tourist.initialize(context, mendixObject);
	}

	public static java.util.List<lets_travel.proxies.Tourist> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> lets_travel.proxies.Tourist.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of DOB
	 */
	public final java.util.Date getDOB()
	{
		return getDOB(getContext());
	}

	/**
	 * @param context
	 * @return value of DOB
	 */
	public final java.util.Date getDOB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DOB.toString());
	}

	/**
	 * Set value of DOB
	 * @param dob
	 */
	public final void setDOB(java.util.Date dob)
	{
		setDOB(getContext(), dob);
	}

	/**
	 * Set value of DOB
	 * @param context
	 * @param dob
	 */
	public final void setDOB(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dob)
	{
		getMendixObject().setValue(context, MemberNames.DOB.toString(), dob);
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * @return value of Phone
	 */
	public final java.lang.String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final java.lang.String getPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(java.lang.String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final lets_travel.proxies.State getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final lets_travel.proxies.State getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.State.toString());
		if (obj == null) {
			return null;
		}
		return lets_travel.proxies.State.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(lets_travel.proxies.State state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.State state)
	{
		if (state != null) {
			getMendixObject().setValue(context, MemberNames.State.toString(), state.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.State.toString(), null);
		}
	}

	/**
	 * Set value of FamilyType
	 * @param familytype
	 */
	public final lets_travel.proxies.Choose_the_Family_Type getFamilyType()
	{
		return getFamilyType(getContext());
	}

	/**
	 * @param context
	 * @return value of FamilyType
	 */
	public final lets_travel.proxies.Choose_the_Family_Type getFamilyType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FamilyType.toString());
		if (obj == null) {
			return null;
		}
		return lets_travel.proxies.Choose_the_Family_Type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FamilyType
	 * @param familytype
	 */
	public final void setFamilyType(lets_travel.proxies.Choose_the_Family_Type familytype)
	{
		setFamilyType(getContext(), familytype);
	}

	/**
	 * Set value of FamilyType
	 * @param context
	 * @param familytype
	 */
	public final void setFamilyType(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.Choose_the_Family_Type familytype)
	{
		if (familytype != null) {
			getMendixObject().setValue(context, MemberNames.FamilyType.toString(), familytype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.FamilyType.toString(), null);
		}
	}

	/**
	 * @return value of Budget
	 */
	public final java.math.BigDecimal getBudget()
	{
		return getBudget(getContext());
	}

	/**
	 * @param context
	 * @return value of Budget
	 */
	public final java.math.BigDecimal getBudget(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Budget.toString());
	}

	/**
	 * Set value of Budget
	 * @param budget
	 */
	public final void setBudget(java.math.BigDecimal budget)
	{
		setBudget(getContext(), budget);
	}

	/**
	 * Set value of Budget
	 * @param context
	 * @param budget
	 */
	public final void setBudget(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal budget)
	{
		getMendixObject().setValue(context, MemberNames.Budget.toString(), budget);
	}

	/**
	 * Set value of states
	 * @param states
	 */
	public final lets_travel.proxies.State getstates()
	{
		return getstates(getContext());
	}

	/**
	 * @param context
	 * @return value of states
	 */
	public final lets_travel.proxies.State getstates(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.states.toString());
		if (obj == null) {
			return null;
		}
		return lets_travel.proxies.State.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of states
	 * @param states
	 */
	public final void setstates(lets_travel.proxies.State states)
	{
		setstates(getContext(), states);
	}

	/**
	 * Set value of states
	 * @param context
	 * @param states
	 */
	public final void setstates(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.State states)
	{
		if (states != null) {
			getMendixObject().setValue(context, MemberNames.states.toString(), states.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.states.toString(), null);
		}
	}

	/**
	 * @return value of ValidateOtp
	 */
	public final java.lang.Integer getValidateOtp()
	{
		return getValidateOtp(getContext());
	}

	/**
	 * @param context
	 * @return value of ValidateOtp
	 */
	public final java.lang.Integer getValidateOtp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ValidateOtp.toString());
	}

	/**
	 * Set value of ValidateOtp
	 * @param validateotp
	 */
	public final void setValidateOtp(java.lang.Integer validateotp)
	{
		setValidateOtp(getContext(), validateotp);
	}

	/**
	 * Set value of ValidateOtp
	 * @param context
	 * @param validateotp
	 */
	public final void setValidateOtp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer validateotp)
	{
		getMendixObject().setValue(context, MemberNames.ValidateOtp.toString(), validateotp);
	}

	/**
	 * @return value of OTP
	 */
	public final java.lang.Integer getOTP()
	{
		return getOTP(getContext());
	}

	/**
	 * @param context
	 * @return value of OTP
	 */
	public final java.lang.Integer getOTP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OTP.toString());
	}

	/**
	 * Set value of OTP
	 * @param otp
	 */
	public final void setOTP(java.lang.Integer otp)
	{
		setOTP(getContext(), otp);
	}

	/**
	 * Set value of OTP
	 * @param context
	 * @param otp
	 */
	public final void setOTP(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer otp)
	{
		getMendixObject().setValue(context, MemberNames.OTP.toString(), otp);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Tourist_Guide
	 */
	public final lets_travel.proxies.Guide getTourist_Guide() throws com.mendix.core.CoreException
	{
		return getTourist_Guide(getContext());
	}

	/**
	 * @param context
	 * @return value of Tourist_Guide
	 * @throws com.mendix.core.CoreException
	 */
	public final lets_travel.proxies.Guide getTourist_Guide(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		lets_travel.proxies.Guide result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Tourist_Guide.toString());
		if (identifier != null) {
			result = lets_travel.proxies.Guide.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Tourist_Guide
	 * @param tourist_guide
	 */
	public final void setTourist_Guide(lets_travel.proxies.Guide tourist_guide)
	{
		setTourist_Guide(getContext(), tourist_guide);
	}

	/**
	 * Set value of Tourist_Guide
	 * @param context
	 * @param tourist_guide
	 */
	public final void setTourist_Guide(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.Guide tourist_guide)
	{
		if (tourist_guide == null) {
			getMendixObject().setValue(context, MemberNames.Tourist_Guide.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Tourist_Guide.toString(), tourist_guide.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TouristProfilePicture_Tourist
	 */
	public final lets_travel.proxies.TouristProfilePicture getTouristProfilePicture_Tourist() throws com.mendix.core.CoreException
	{
		return getTouristProfilePicture_Tourist(getContext());
	}

	/**
	 * @param context
	 * @return value of TouristProfilePicture_Tourist
	 * @throws com.mendix.core.CoreException
	 */
	public final lets_travel.proxies.TouristProfilePicture getTouristProfilePicture_Tourist(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		lets_travel.proxies.TouristProfilePicture result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TouristProfilePicture_Tourist.toString());
		if (identifier != null) {
			result = lets_travel.proxies.TouristProfilePicture.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TouristProfilePicture_Tourist
	 * @param touristprofilepicture_tourist
	 */
	public final void setTouristProfilePicture_Tourist(lets_travel.proxies.TouristProfilePicture touristprofilepicture_tourist)
	{
		setTouristProfilePicture_Tourist(getContext(), touristprofilepicture_tourist);
	}

	/**
	 * Set value of TouristProfilePicture_Tourist
	 * @param context
	 * @param touristprofilepicture_tourist
	 */
	public final void setTouristProfilePicture_Tourist(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.TouristProfilePicture touristprofilepicture_tourist)
	{
		if (touristprofilepicture_tourist == null) {
			getMendixObject().setValue(context, MemberNames.TouristProfilePicture_Tourist.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TouristProfilePicture_Tourist.toString(), touristprofilepicture_tourist.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final lets_travel.proxies.Tourist that = (lets_travel.proxies.Tourist) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
