// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package lets_travel.proxies;

public class Tourist_npe
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tourist_npeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Lets_Travel.Tourist_npe";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		DOB("DOB"),
		Address("Address"),
		Email("Email"),
		Password("Password"),
		ConfirmPassword("ConfirmPassword"),
		State("State"),
		Phone("Phone"),
		countries("countries"),
		FamilyType("FamilyType"),
		Budget("Budget"),
		OTP("OTP"),
		Number("Number");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Tourist_npe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Tourist_npe(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tourist_npeMendixObject)
	{
		if (tourist_npeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, tourist_npeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.tourist_npeMendixObject = tourist_npeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Tourist_npe.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static lets_travel.proxies.Tourist_npe initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return lets_travel.proxies.Tourist_npe.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static lets_travel.proxies.Tourist_npe initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new lets_travel.proxies.Tourist_npe(context, mendixObject);
	}

	public static lets_travel.proxies.Tourist_npe load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return lets_travel.proxies.Tourist_npe.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of DOB
	 */
	public final java.util.Date getDOB()
	{
		return getDOB(getContext());
	}

	/**
	 * @param context
	 * @return value of DOB
	 */
	public final java.util.Date getDOB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DOB.toString());
	}

	/**
	 * Set value of DOB
	 * @param dob
	 */
	public final void setDOB(java.util.Date dob)
	{
		setDOB(getContext(), dob);
	}

	/**
	 * Set value of DOB
	 * @param context
	 * @param dob
	 */
	public final void setDOB(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dob)
	{
		getMendixObject().setValue(context, MemberNames.DOB.toString(), dob);
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of ConfirmPassword
	 */
	public final java.lang.String getConfirmPassword()
	{
		return getConfirmPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfirmPassword
	 */
	public final java.lang.String getConfirmPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConfirmPassword.toString());
	}

	/**
	 * Set value of ConfirmPassword
	 * @param confirmpassword
	 */
	public final void setConfirmPassword(java.lang.String confirmpassword)
	{
		setConfirmPassword(getContext(), confirmpassword);
	}

	/**
	 * Set value of ConfirmPassword
	 * @param context
	 * @param confirmpassword
	 */
	public final void setConfirmPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String confirmpassword)
	{
		getMendixObject().setValue(context, MemberNames.ConfirmPassword.toString(), confirmpassword);
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final lets_travel.proxies.State getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final lets_travel.proxies.State getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.State.toString());
		if (obj == null) {
			return null;
		}
		return lets_travel.proxies.State.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(lets_travel.proxies.State state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.State state)
	{
		if (state != null) {
			getMendixObject().setValue(context, MemberNames.State.toString(), state.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.State.toString(), null);
		}
	}

	/**
	 * @return value of Phone
	 */
	public final java.lang.String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final java.lang.String getPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(java.lang.String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * Set value of countries
	 * @param countries
	 */
	public final lets_travel.proxies.Countries getcountries()
	{
		return getcountries(getContext());
	}

	/**
	 * @param context
	 * @return value of countries
	 */
	public final lets_travel.proxies.Countries getcountries(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.countries.toString());
		if (obj == null) {
			return null;
		}
		return lets_travel.proxies.Countries.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of countries
	 * @param countries
	 */
	public final void setcountries(lets_travel.proxies.Countries countries)
	{
		setcountries(getContext(), countries);
	}

	/**
	 * Set value of countries
	 * @param context
	 * @param countries
	 */
	public final void setcountries(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.Countries countries)
	{
		if (countries != null) {
			getMendixObject().setValue(context, MemberNames.countries.toString(), countries.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.countries.toString(), null);
		}
	}

	/**
	 * Set value of FamilyType
	 * @param familytype
	 */
	public final lets_travel.proxies.Choose_the_Family_Type getFamilyType()
	{
		return getFamilyType(getContext());
	}

	/**
	 * @param context
	 * @return value of FamilyType
	 */
	public final lets_travel.proxies.Choose_the_Family_Type getFamilyType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FamilyType.toString());
		if (obj == null) {
			return null;
		}
		return lets_travel.proxies.Choose_the_Family_Type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FamilyType
	 * @param familytype
	 */
	public final void setFamilyType(lets_travel.proxies.Choose_the_Family_Type familytype)
	{
		setFamilyType(getContext(), familytype);
	}

	/**
	 * Set value of FamilyType
	 * @param context
	 * @param familytype
	 */
	public final void setFamilyType(com.mendix.systemwideinterfaces.core.IContext context, lets_travel.proxies.Choose_the_Family_Type familytype)
	{
		if (familytype != null) {
			getMendixObject().setValue(context, MemberNames.FamilyType.toString(), familytype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.FamilyType.toString(), null);
		}
	}

	/**
	 * @return value of Budget
	 */
	public final java.math.BigDecimal getBudget()
	{
		return getBudget(getContext());
	}

	/**
	 * @param context
	 * @return value of Budget
	 */
	public final java.math.BigDecimal getBudget(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Budget.toString());
	}

	/**
	 * Set value of Budget
	 * @param budget
	 */
	public final void setBudget(java.math.BigDecimal budget)
	{
		setBudget(getContext(), budget);
	}

	/**
	 * Set value of Budget
	 * @param context
	 * @param budget
	 */
	public final void setBudget(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal budget)
	{
		getMendixObject().setValue(context, MemberNames.Budget.toString(), budget);
	}

	/**
	 * @return value of OTP
	 */
	public final java.lang.Integer getOTP()
	{
		return getOTP(getContext());
	}

	/**
	 * @param context
	 * @return value of OTP
	 */
	public final java.lang.Integer getOTP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OTP.toString());
	}

	/**
	 * Set value of OTP
	 * @param otp
	 */
	public final void setOTP(java.lang.Integer otp)
	{
		setOTP(getContext(), otp);
	}

	/**
	 * Set value of OTP
	 * @param context
	 * @param otp
	 */
	public final void setOTP(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer otp)
	{
		getMendixObject().setValue(context, MemberNames.OTP.toString(), otp);
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Integer number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tourist_npeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final lets_travel.proxies.Tourist_npe that = (lets_travel.proxies.Tourist_npe) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
