// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailtemplate.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the EmailTemplate module

	public static java.lang.String getazure_emailServerHostURL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EmailTemplate.azure_emailServerHostURL");
	}

	public static java.lang.String getEmailAddressSeparator()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EmailTemplate.EmailAddressSeparator");
	}

	/**
	* The amount of days to preserve error messages.
	*/
	public static java.lang.Long getEmailLogRetention()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("EmailTemplate.EmailLogRetention");
	}

	/**
	* The amount of days to preserve emails which were sent.
	*/
	public static java.lang.Long getEmailRetention()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("EmailTemplate.EmailRetention");
	}

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EmailTemplate.LogNode");
	}

	/**
	* Sending emails is enabled by default. 
	* When setting this value to false emails won't be send. This is useful on test environments for example.
	*/
	public static boolean getSendingEnabled()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("EmailTemplate.SendingEnabled");
	}
}