// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package lets_travel.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Lets_Travel module
	public static void aCT_ConfirmGuideRegistration(IContext context, lets_travel.proxies.Guide_npe _gUIDE_REGISTRATION)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GUIDE_REGISTRATION", _gUIDE_REGISTRATION == null ? null : _gUIDE_REGISTRATION.getMendixObject());
		Core.microflowCall("Lets_Travel.ACT_ConfirmGuideRegistration").withParams(params).execute(context);
	}
	public static void aCT_ConfirmTouristRegistration(IContext context, lets_travel.proxies.Tourist_npe _tOURIST_REGISTRATION)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TOURIST_REGISTRATION", _tOURIST_REGISTRATION == null ? null : _tOURIST_REGISTRATION.getMendixObject());
		Core.microflowCall("Lets_Travel.ACT_ConfirmTouristRegistration").withParams(params).execute(context);
	}
	public static void aCT_CreateRegistrationGuide(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Lets_Travel.ACT_CreateRegistrationGuide").withParams(params).execute(context);
	}
	public static void aCT_CreateRegistrationTourist(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Lets_Travel.ACT_CreateRegistrationTourist").withParams(params).execute(context);
	}
	public static void aCT_REGISTRATION_SENDEMAIL(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Lets_Travel.ACT_REGISTRATION_SENDEMAIL").withParams(params).execute(context);
	}
	public static boolean bookFormValidateMicroflow(IContext context, lets_travel.proxies.TouristBookingDetails _touristBookingDetails)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TouristBookingDetails", _touristBookingDetails == null ? null : _touristBookingDetails.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Lets_Travel.BookFormValidateMicroflow").withParams(params).execute(context);
	}
	public static void createandRetrieveGuideData(IContext context, lets_travel.proxies.Guide_npe _gUIDE_REGISTRATION)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GUIDE_REGISTRATION", _gUIDE_REGISTRATION == null ? null : _gUIDE_REGISTRATION.getMendixObject());
		Core.microflowCall("Lets_Travel.CreateandRetrieveGuideData").withParams(params).execute(context);
	}
	public static void createandRetrieveTouristData(IContext context, lets_travel.proxies.Tourist_npe _tOURIST_REGISTRATION)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TOURIST_REGISTRATION", _tOURIST_REGISTRATION == null ? null : _tOURIST_REGISTRATION.getMendixObject());
		Core.microflowCall("Lets_Travel.CreateandRetrieveTouristData").withParams(params).execute(context);
	}
	public static void createBookingDetailsObject(IContext context, lets_travel.proxies.TouristBookingDetails _touristBookingDetails)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TouristBookingDetails", _touristBookingDetails == null ? null : _touristBookingDetails.getMendixObject());
		Core.microflowCall("Lets_Travel.createBookingDetailsObject").withParams(params).execute(context);
	}
	public static boolean deletingTheBookedGuide(IContext context, lets_travel.proxies.TouristBookingDetails _touristBookingDetails)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TouristBookingDetails", _touristBookingDetails == null ? null : _touristBookingDetails.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Lets_Travel.DeletingTheBookedGuide").withParams(params).execute(context);
	}
	public static void deletingTheBooking(IContext context, lets_travel.proxies.TouristBookingDetails _touristBookingDetails)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TouristBookingDetails", _touristBookingDetails == null ? null : _touristBookingDetails.getMendixObject());
		Core.microflowCall("Lets_Travel.deletingTheBooking").withParams(params).execute(context);
	}
	public static lets_travel.proxies.LoginHelper dS_LoginHelper(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Lets_Travel.DS_LoginHelper").withParams(params).execute(context);
		return result == null ? null : lets_travel.proxies.LoginHelper.initialize(context, result);
	}
	public static void editBookingMicroflow(IContext context, lets_travel.proxies.TouristBookingDetails _touristBookingDetails)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TouristBookingDetails", _touristBookingDetails == null ? null : _touristBookingDetails.getMendixObject());
		Core.microflowCall("Lets_Travel.editBookingMicroflow").withParams(params).execute(context);
	}
	public static void editGuideProfile(IContext context, lets_travel.proxies.Guide _guide)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Guide", _guide == null ? null : _guide.getMendixObject());
		Core.microflowCall("Lets_Travel.editGuideProfile").withParams(params).execute(context);
	}
	public static void editTouristProfileData(IContext context, lets_travel.proxies.Tourist _tourist)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Tourist", _tourist == null ? null : _tourist.getMendixObject());
		Core.microflowCall("Lets_Travel.editTouristProfileData").withParams(params).execute(context);
	}
	public static void gUIDEMICROFLOW2(IContext context, lets_travel.proxies.Guide _guide)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Guide", _guide == null ? null : _guide.getMendixObject());
		Core.microflowCall("Lets_Travel.GUIDEMICROFLOW2").withParams(params).execute(context);
	}
	public static void microflow(IContext context, lets_travel.proxies.cities _cities)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("cities", _cities == null ? null : _cities.getMendixObject());
		Core.microflowCall("Lets_Travel.Microflow").withParams(params).execute(context);
	}
	public static void mymicro1(IContext context, lets_travel.proxies.Guide _guide, lets_travel.proxies.cities _cities)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Guide", _guide == null ? null : _guide.getMendixObject());
		params.put("cities", _cities == null ? null : _cities.getMendixObject());
		Core.microflowCall("Lets_Travel.mymicro1").withParams(params).execute(context);
	}
	public static void retrieve_admin_profile(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Lets_Travel.retrieve_admin_profile").withParams(params).execute(context);
	}
	public static void retrive_guide_profile(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Lets_Travel.retrive_guide_profile").withParams(params).execute(context);
	}
	public static void retrive_tourist_profile(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Lets_Travel.retrive_tourist_profile").withParams(params).execute(context);
	}
	public static void send_tourist_update_to_guide(IContext context, lets_travel.proxies.TouristBookingDetails _touristBookingDetails)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TouristBookingDetails", _touristBookingDetails == null ? null : _touristBookingDetails.getMendixObject());
		Core.microflowCall("Lets_Travel.send_tourist_update_to_guide").withParams(params).execute(context);
	}
	public static void sendEmailByTourist(IContext context, lets_travel.proxies.EmailHelper _emailHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailHelper", _emailHelper == null ? null : _emailHelper.getMendixObject());
		Core.microflowCall("Lets_Travel.sendEmailByTourist").withParams(params).execute(context);
	}
	public static void sub_CreateAndSendEmail(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate, lets_travel.proxies.EmailHelper _emailHelper, java.lang.String _emailAddress)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
		params.put("EmailHelper", _emailHelper == null ? null : _emailHelper.getMendixObject());
		params.put("EmailAddress", _emailAddress);
		Core.microflowCall("Lets_Travel.Sub_CreateAndSendEmail").withParams(params).execute(context);
	}
	public static void takingMailForGuide(IContext context, lets_travel.proxies.TouristBookingDetails _touristBookingDetails)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TouristBookingDetails", _touristBookingDetails == null ? null : _touristBookingDetails.getMendixObject());
		Core.microflowCall("Lets_Travel.TakingMailForGuide").withParams(params).execute(context);
	}
	public static void tOURISTMICROFLOW2(IContext context, lets_travel.proxies.Tourist _tourist)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Tourist", _tourist == null ? null : _tourist.getMendixObject());
		Core.microflowCall("Lets_Travel.TOURISTMICROFLOW2").withParams(params).execute(context);
	}
	public static void touristvalidationgOtp(IContext context, lets_travel.proxies.Tourist _tOURIST_REGISTRATION)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TOURIST_REGISTRATION", _tOURIST_REGISTRATION == null ? null : _tOURIST_REGISTRATION.getMendixObject());
		Core.microflowCall("Lets_Travel.TouristvalidationgOtp").withParams(params).execute(context);
	}
	public static boolean validate_GuideRegistration(IContext context, lets_travel.proxies.Guide_npe _guideRegistration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GuideRegistration", _guideRegistration == null ? null : _guideRegistration.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Lets_Travel.Validate_GuideRegistration").withParams(params).execute(context);
	}
	public static boolean validate_TouristRegistration(IContext context, lets_travel.proxies.Tourist_npe _touristRegistration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TouristRegistration", _touristRegistration == null ? null : _touristRegistration.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Lets_Travel.Validate_TouristRegistration").withParams(params).execute(context);
	}
	public static void validatingOtp(IContext context, lets_travel.proxies.Guide _gUIDE_REGISTRATION)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GUIDE_REGISTRATION", _gUIDE_REGISTRATION == null ? null : _gUIDE_REGISTRATION.getMendixObject());
		Core.microflowCall("Lets_Travel.validatingOtp").withParams(params).execute(context);
	}
}
