// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailtemplate.proxies;

public class EmailSettings
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject emailSettingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmailTemplate.EmailSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UserName("UserName"),
		Password("Password"),
		Server("Server"),
		Port("Port"),
		FromAddress("FromAddress"),
		FromDisplayName("FromDisplayName"),
		UseSSL("UseSSL"),
		UseTLS("UseTLS"),
		MaxAttempts("MaxAttempts"),
		UseSSLCheckServerIdentity("UseSSLCheckServerIdentity"),
		isOAuthUsed("isOAuthUsed"),
		EmailSettings_OAuthProviderDetails("EmailTemplate.EmailSettings_OAuthProviderDetails"),
		Token_EmailSettings("EmailTemplate.Token_EmailSettings");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmailSettings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmailSettings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject emailSettingsMendixObject)
	{
		if (emailSettingsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, emailSettingsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.emailSettingsMendixObject = emailSettingsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EmailSettings.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emailtemplate.proxies.EmailSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emailtemplate.proxies.EmailSettings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static emailtemplate.proxies.EmailSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emailtemplate.proxies.EmailSettings(context, mendixObject);
	}

	public static emailtemplate.proxies.EmailSettings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emailtemplate.proxies.EmailSettings.initialize(context, mendixObject);
	}

	public static java.util.List<emailtemplate.proxies.EmailSettings> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> emailtemplate.proxies.EmailSettings.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UserName
	 */
	public final java.lang.String getUserName()
	{
		return getUserName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserName
	 */
	public final java.lang.String getUserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserName.toString());
	}

	/**
	 * Set value of UserName
	 * @param username
	 */
	public final void setUserName(java.lang.String username)
	{
		setUserName(getContext(), username);
	}

	/**
	 * Set value of UserName
	 * @param context
	 * @param username
	 */
	public final void setUserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.UserName.toString(), username);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of Server
	 */
	public final java.lang.String getServer()
	{
		return getServer(getContext());
	}

	/**
	 * @param context
	 * @return value of Server
	 */
	public final java.lang.String getServer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Server.toString());
	}

	/**
	 * Set value of Server
	 * @param server
	 */
	public final void setServer(java.lang.String server)
	{
		setServer(getContext(), server);
	}

	/**
	 * Set value of Server
	 * @param context
	 * @param server
	 */
	public final void setServer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String server)
	{
		getMendixObject().setValue(context, MemberNames.Server.toString(), server);
	}

	/**
	 * @return value of Port
	 */
	public final java.lang.Integer getPort()
	{
		return getPort(getContext());
	}

	/**
	 * @param context
	 * @return value of Port
	 */
	public final java.lang.Integer getPort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Port.toString());
	}

	/**
	 * Set value of Port
	 * @param port
	 */
	public final void setPort(java.lang.Integer port)
	{
		setPort(getContext(), port);
	}

	/**
	 * Set value of Port
	 * @param context
	 * @param port
	 */
	public final void setPort(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer port)
	{
		getMendixObject().setValue(context, MemberNames.Port.toString(), port);
	}

	/**
	 * @return value of FromAddress
	 */
	public final java.lang.String getFromAddress()
	{
		return getFromAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of FromAddress
	 */
	public final java.lang.String getFromAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FromAddress.toString());
	}

	/**
	 * Set value of FromAddress
	 * @param fromaddress
	 */
	public final void setFromAddress(java.lang.String fromaddress)
	{
		setFromAddress(getContext(), fromaddress);
	}

	/**
	 * Set value of FromAddress
	 * @param context
	 * @param fromaddress
	 */
	public final void setFromAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fromaddress)
	{
		getMendixObject().setValue(context, MemberNames.FromAddress.toString(), fromaddress);
	}

	/**
	 * @return value of FromDisplayName
	 */
	public final java.lang.String getFromDisplayName()
	{
		return getFromDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of FromDisplayName
	 */
	public final java.lang.String getFromDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FromDisplayName.toString());
	}

	/**
	 * Set value of FromDisplayName
	 * @param fromdisplayname
	 */
	public final void setFromDisplayName(java.lang.String fromdisplayname)
	{
		setFromDisplayName(getContext(), fromdisplayname);
	}

	/**
	 * Set value of FromDisplayName
	 * @param context
	 * @param fromdisplayname
	 */
	public final void setFromDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fromdisplayname)
	{
		getMendixObject().setValue(context, MemberNames.FromDisplayName.toString(), fromdisplayname);
	}

	/**
	 * @return value of UseSSL
	 */
	public final java.lang.Boolean getUseSSL()
	{
		return getUseSSL(getContext());
	}

	/**
	 * @param context
	 * @return value of UseSSL
	 */
	public final java.lang.Boolean getUseSSL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseSSL.toString());
	}

	/**
	 * Set value of UseSSL
	 * @param usessl
	 */
	public final void setUseSSL(java.lang.Boolean usessl)
	{
		setUseSSL(getContext(), usessl);
	}

	/**
	 * Set value of UseSSL
	 * @param context
	 * @param usessl
	 */
	public final void setUseSSL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean usessl)
	{
		getMendixObject().setValue(context, MemberNames.UseSSL.toString(), usessl);
	}

	/**
	 * @return value of UseTLS
	 */
	public final java.lang.Boolean getUseTLS()
	{
		return getUseTLS(getContext());
	}

	/**
	 * @param context
	 * @return value of UseTLS
	 */
	public final java.lang.Boolean getUseTLS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseTLS.toString());
	}

	/**
	 * Set value of UseTLS
	 * @param usetls
	 */
	public final void setUseTLS(java.lang.Boolean usetls)
	{
		setUseTLS(getContext(), usetls);
	}

	/**
	 * Set value of UseTLS
	 * @param context
	 * @param usetls
	 */
	public final void setUseTLS(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean usetls)
	{
		getMendixObject().setValue(context, MemberNames.UseTLS.toString(), usetls);
	}

	/**
	 * @return value of MaxAttempts
	 */
	public final java.lang.Integer getMaxAttempts()
	{
		return getMaxAttempts(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxAttempts
	 */
	public final java.lang.Integer getMaxAttempts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxAttempts.toString());
	}

	/**
	 * Set value of MaxAttempts
	 * @param maxattempts
	 */
	public final void setMaxAttempts(java.lang.Integer maxattempts)
	{
		setMaxAttempts(getContext(), maxattempts);
	}

	/**
	 * Set value of MaxAttempts
	 * @param context
	 * @param maxattempts
	 */
	public final void setMaxAttempts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxattempts)
	{
		getMendixObject().setValue(context, MemberNames.MaxAttempts.toString(), maxattempts);
	}

	/**
	 * @return value of UseSSLCheckServerIdentity
	 */
	public final java.lang.Boolean getUseSSLCheckServerIdentity()
	{
		return getUseSSLCheckServerIdentity(getContext());
	}

	/**
	 * @param context
	 * @return value of UseSSLCheckServerIdentity
	 */
	public final java.lang.Boolean getUseSSLCheckServerIdentity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseSSLCheckServerIdentity.toString());
	}

	/**
	 * Set value of UseSSLCheckServerIdentity
	 * @param usesslcheckserveridentity
	 */
	public final void setUseSSLCheckServerIdentity(java.lang.Boolean usesslcheckserveridentity)
	{
		setUseSSLCheckServerIdentity(getContext(), usesslcheckserveridentity);
	}

	/**
	 * Set value of UseSSLCheckServerIdentity
	 * @param context
	 * @param usesslcheckserveridentity
	 */
	public final void setUseSSLCheckServerIdentity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean usesslcheckserveridentity)
	{
		getMendixObject().setValue(context, MemberNames.UseSSLCheckServerIdentity.toString(), usesslcheckserveridentity);
	}

	/**
	 * @return value of isOAuthUsed
	 */
	public final java.lang.Boolean getisOAuthUsed()
	{
		return getisOAuthUsed(getContext());
	}

	/**
	 * @param context
	 * @return value of isOAuthUsed
	 */
	public final java.lang.Boolean getisOAuthUsed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isOAuthUsed.toString());
	}

	/**
	 * Set value of isOAuthUsed
	 * @param isoauthused
	 */
	public final void setisOAuthUsed(java.lang.Boolean isoauthused)
	{
		setisOAuthUsed(getContext(), isoauthused);
	}

	/**
	 * Set value of isOAuthUsed
	 * @param context
	 * @param isoauthused
	 */
	public final void setisOAuthUsed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isoauthused)
	{
		getMendixObject().setValue(context, MemberNames.isOAuthUsed.toString(), isoauthused);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmailSettings_OAuthProviderDetails
	 */
	public final emailtemplate.proxies.OAuthProviderDetails getEmailSettings_OAuthProviderDetails() throws com.mendix.core.CoreException
	{
		return getEmailSettings_OAuthProviderDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailSettings_OAuthProviderDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final emailtemplate.proxies.OAuthProviderDetails getEmailSettings_OAuthProviderDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emailtemplate.proxies.OAuthProviderDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmailSettings_OAuthProviderDetails.toString());
		if (identifier != null) {
			result = emailtemplate.proxies.OAuthProviderDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmailSettings_OAuthProviderDetails
	 * @param emailsettings_oauthproviderdetails
	 */
	public final void setEmailSettings_OAuthProviderDetails(emailtemplate.proxies.OAuthProviderDetails emailsettings_oauthproviderdetails)
	{
		setEmailSettings_OAuthProviderDetails(getContext(), emailsettings_oauthproviderdetails);
	}

	/**
	 * Set value of EmailSettings_OAuthProviderDetails
	 * @param context
	 * @param emailsettings_oauthproviderdetails
	 */
	public final void setEmailSettings_OAuthProviderDetails(com.mendix.systemwideinterfaces.core.IContext context, emailtemplate.proxies.OAuthProviderDetails emailsettings_oauthproviderdetails)
	{
		if (emailsettings_oauthproviderdetails == null) {
			getMendixObject().setValue(context, MemberNames.EmailSettings_OAuthProviderDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmailSettings_OAuthProviderDetails.toString(), emailsettings_oauthproviderdetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Token_EmailSettings
	 */
	public final emailtemplate.proxies.Token getToken_EmailSettings() throws com.mendix.core.CoreException
	{
		return getToken_EmailSettings(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_EmailSettings
	 * @throws com.mendix.core.CoreException
	 */
	public final emailtemplate.proxies.Token getToken_EmailSettings(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emailtemplate.proxies.Token result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Token_EmailSettings.toString());
		if (identifier != null) {
			result = emailtemplate.proxies.Token.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Token_EmailSettings
	 * @param token_emailsettings
	 */
	public final void setToken_EmailSettings(emailtemplate.proxies.Token token_emailsettings)
	{
		setToken_EmailSettings(getContext(), token_emailsettings);
	}

	/**
	 * Set value of Token_EmailSettings
	 * @param context
	 * @param token_emailsettings
	 */
	public final void setToken_EmailSettings(com.mendix.systemwideinterfaces.core.IContext context, emailtemplate.proxies.Token token_emailsettings)
	{
		if (token_emailsettings == null) {
			getMendixObject().setValue(context, MemberNames.Token_EmailSettings.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Token_EmailSettings.toString(), token_emailsettings.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return emailSettingsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emailtemplate.proxies.EmailSettings that = (emailtemplate.proxies.EmailSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
