// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailtemplate.proxies;

public class ModuleSetup
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject moduleSetupMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmailTemplate.ModuleSetup";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Completed("Completed"),
		NrOfTemplates("NrOfTemplates"),
		SentSuccessful("SentSuccessful"),
		ModuleSetup_EmailSettings("EmailTemplate.ModuleSetup_EmailSettings");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ModuleSetup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ModuleSetup(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject moduleSetupMendixObject)
	{
		if (moduleSetupMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, moduleSetupMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.moduleSetupMendixObject = moduleSetupMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ModuleSetup.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emailtemplate.proxies.ModuleSetup initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emailtemplate.proxies.ModuleSetup.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static emailtemplate.proxies.ModuleSetup initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emailtemplate.proxies.ModuleSetup(context, mendixObject);
	}

	public static emailtemplate.proxies.ModuleSetup load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emailtemplate.proxies.ModuleSetup.initialize(context, mendixObject);
	}

	public static java.util.List<emailtemplate.proxies.ModuleSetup> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> emailtemplate.proxies.ModuleSetup.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Completed
	 */
	public final java.lang.Boolean getCompleted()
	{
		return getCompleted(getContext());
	}

	/**
	 * @param context
	 * @return value of Completed
	 */
	public final java.lang.Boolean getCompleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Completed.toString());
	}

	/**
	 * Set value of Completed
	 * @param completed
	 */
	public final void setCompleted(java.lang.Boolean completed)
	{
		setCompleted(getContext(), completed);
	}

	/**
	 * Set value of Completed
	 * @param context
	 * @param completed
	 */
	public final void setCompleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean completed)
	{
		getMendixObject().setValue(context, MemberNames.Completed.toString(), completed);
	}

	/**
	 * @return value of NrOfTemplates
	 */
	public final java.lang.Integer getNrOfTemplates()
	{
		return getNrOfTemplates(getContext());
	}

	/**
	 * @param context
	 * @return value of NrOfTemplates
	 */
	public final java.lang.Integer getNrOfTemplates(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NrOfTemplates.toString());
	}

	/**
	 * Set value of NrOfTemplates
	 * @param nroftemplates
	 */
	public final void setNrOfTemplates(java.lang.Integer nroftemplates)
	{
		setNrOfTemplates(getContext(), nroftemplates);
	}

	/**
	 * Set value of NrOfTemplates
	 * @param context
	 * @param nroftemplates
	 */
	public final void setNrOfTemplates(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nroftemplates)
	{
		getMendixObject().setValue(context, MemberNames.NrOfTemplates.toString(), nroftemplates);
	}

	/**
	 * @return value of SentSuccessful
	 */
	public final java.lang.Boolean getSentSuccessful()
	{
		return getSentSuccessful(getContext());
	}

	/**
	 * @param context
	 * @return value of SentSuccessful
	 */
	public final java.lang.Boolean getSentSuccessful(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SentSuccessful.toString());
	}

	/**
	 * Set value of SentSuccessful
	 * @param sentsuccessful
	 */
	public final void setSentSuccessful(java.lang.Boolean sentsuccessful)
	{
		setSentSuccessful(getContext(), sentsuccessful);
	}

	/**
	 * Set value of SentSuccessful
	 * @param context
	 * @param sentsuccessful
	 */
	public final void setSentSuccessful(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean sentsuccessful)
	{
		getMendixObject().setValue(context, MemberNames.SentSuccessful.toString(), sentsuccessful);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ModuleSetup_EmailSettings
	 */
	public final emailtemplate.proxies.EmailSettings getModuleSetup_EmailSettings() throws com.mendix.core.CoreException
	{
		return getModuleSetup_EmailSettings(getContext());
	}

	/**
	 * @param context
	 * @return value of ModuleSetup_EmailSettings
	 * @throws com.mendix.core.CoreException
	 */
	public final emailtemplate.proxies.EmailSettings getModuleSetup_EmailSettings(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emailtemplate.proxies.EmailSettings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ModuleSetup_EmailSettings.toString());
		if (identifier != null) {
			result = emailtemplate.proxies.EmailSettings.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ModuleSetup_EmailSettings
	 * @param modulesetup_emailsettings
	 */
	public final void setModuleSetup_EmailSettings(emailtemplate.proxies.EmailSettings modulesetup_emailsettings)
	{
		setModuleSetup_EmailSettings(getContext(), modulesetup_emailsettings);
	}

	/**
	 * Set value of ModuleSetup_EmailSettings
	 * @param context
	 * @param modulesetup_emailsettings
	 */
	public final void setModuleSetup_EmailSettings(com.mendix.systemwideinterfaces.core.IContext context, emailtemplate.proxies.EmailSettings modulesetup_emailsettings)
	{
		if (modulesetup_emailsettings == null) {
			getMendixObject().setValue(context, MemberNames.ModuleSetup_EmailSettings.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ModuleSetup_EmailSettings.toString(), modulesetup_emailsettings.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return moduleSetupMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emailtemplate.proxies.ModuleSetup that = (emailtemplate.proxies.ModuleSetup) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
