// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailtemplate.proxies;

public class OAuthPayload
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject oAuthPayloadMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmailTemplate.OAuthPayload";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		payload("payload"),
		emailAddress("emailAddress"),
		provider("provider"),
		isReAuthPayload("isReAuthPayload"),
		reauthAccountId("reauthAccountId"),
		OAuthPayload_Session("EmailTemplate.OAuthPayload_Session");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OAuthPayload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OAuthPayload(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject oAuthPayloadMendixObject)
	{
		if (oAuthPayloadMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, oAuthPayloadMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.oAuthPayloadMendixObject = oAuthPayloadMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'OAuthPayload.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emailtemplate.proxies.OAuthPayload initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emailtemplate.proxies.OAuthPayload.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static emailtemplate.proxies.OAuthPayload initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emailtemplate.proxies.OAuthPayload(context, mendixObject);
	}

	public static emailtemplate.proxies.OAuthPayload load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emailtemplate.proxies.OAuthPayload.initialize(context, mendixObject);
	}

	public static java.util.List<emailtemplate.proxies.OAuthPayload> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> emailtemplate.proxies.OAuthPayload.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of payload
	 */
	public final java.lang.String getpayload()
	{
		return getpayload(getContext());
	}

	/**
	 * @param context
	 * @return value of payload
	 */
	public final java.lang.String getpayload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.payload.toString());
	}

	/**
	 * Set value of payload
	 * @param payload
	 */
	public final void setpayload(java.lang.String payload)
	{
		setpayload(getContext(), payload);
	}

	/**
	 * Set value of payload
	 * @param context
	 * @param payload
	 */
	public final void setpayload(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payload)
	{
		getMendixObject().setValue(context, MemberNames.payload.toString(), payload);
	}

	/**
	 * @return value of emailAddress
	 */
	public final java.lang.String getemailAddress()
	{
		return getemailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of emailAddress
	 */
	public final java.lang.String getemailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.emailAddress.toString());
	}

	/**
	 * Set value of emailAddress
	 * @param emailaddress
	 */
	public final void setemailAddress(java.lang.String emailaddress)
	{
		setemailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of emailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setemailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.emailAddress.toString(), emailaddress);
	}

	/**
	 * Set value of provider
	 * @param provider
	 */
	public final emailtemplate.proxies.SupportedOAuthProvider getprovider()
	{
		return getprovider(getContext());
	}

	/**
	 * @param context
	 * @return value of provider
	 */
	public final emailtemplate.proxies.SupportedOAuthProvider getprovider(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.provider.toString());
		if (obj == null) {
			return null;
		}
		return emailtemplate.proxies.SupportedOAuthProvider.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of provider
	 * @param provider
	 */
	public final void setprovider(emailtemplate.proxies.SupportedOAuthProvider provider)
	{
		setprovider(getContext(), provider);
	}

	/**
	 * Set value of provider
	 * @param context
	 * @param provider
	 */
	public final void setprovider(com.mendix.systemwideinterfaces.core.IContext context, emailtemplate.proxies.SupportedOAuthProvider provider)
	{
		if (provider != null) {
			getMendixObject().setValue(context, MemberNames.provider.toString(), provider.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.provider.toString(), null);
		}
	}

	/**
	 * @return value of isReAuthPayload
	 */
	public final java.lang.Boolean getisReAuthPayload()
	{
		return getisReAuthPayload(getContext());
	}

	/**
	 * @param context
	 * @return value of isReAuthPayload
	 */
	public final java.lang.Boolean getisReAuthPayload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isReAuthPayload.toString());
	}

	/**
	 * Set value of isReAuthPayload
	 * @param isreauthpayload
	 */
	public final void setisReAuthPayload(java.lang.Boolean isreauthpayload)
	{
		setisReAuthPayload(getContext(), isreauthpayload);
	}

	/**
	 * Set value of isReAuthPayload
	 * @param context
	 * @param isreauthpayload
	 */
	public final void setisReAuthPayload(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isreauthpayload)
	{
		getMendixObject().setValue(context, MemberNames.isReAuthPayload.toString(), isreauthpayload);
	}

	/**
	 * @return value of reauthAccountId
	 */
	public final java.lang.String getreauthAccountId()
	{
		return getreauthAccountId(getContext());
	}

	/**
	 * @param context
	 * @return value of reauthAccountId
	 */
	public final java.lang.String getreauthAccountId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.reauthAccountId.toString());
	}

	/**
	 * Set value of reauthAccountId
	 * @param reauthaccountid
	 */
	public final void setreauthAccountId(java.lang.String reauthaccountid)
	{
		setreauthAccountId(getContext(), reauthaccountid);
	}

	/**
	 * Set value of reauthAccountId
	 * @param context
	 * @param reauthaccountid
	 */
	public final void setreauthAccountId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reauthaccountid)
	{
		getMendixObject().setValue(context, MemberNames.reauthAccountId.toString(), reauthaccountid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OAuthPayload_Session
	 */
	public final system.proxies.Session getOAuthPayload_Session() throws com.mendix.core.CoreException
	{
		return getOAuthPayload_Session(getContext());
	}

	/**
	 * @param context
	 * @return value of OAuthPayload_Session
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Session getOAuthPayload_Session(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Session result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OAuthPayload_Session.toString());
		if (identifier != null) {
			result = system.proxies.Session.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OAuthPayload_Session
	 * @param oauthpayload_session
	 */
	public final void setOAuthPayload_Session(system.proxies.Session oauthpayload_session)
	{
		setOAuthPayload_Session(getContext(), oauthpayload_session);
	}

	/**
	 * Set value of OAuthPayload_Session
	 * @param context
	 * @param oauthpayload_session
	 */
	public final void setOAuthPayload_Session(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Session oauthpayload_session)
	{
		if (oauthpayload_session == null) {
			getMendixObject().setValue(context, MemberNames.OAuthPayload_Session.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OAuthPayload_Session.toString(), oauthpayload_session.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return oAuthPayloadMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emailtemplate.proxies.OAuthPayload that = (emailtemplate.proxies.OAuthPayload) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
