// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailtemplate.proxies;

public class TestMessage
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testMessageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmailTemplate.TestMessage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		From("From"),
		To("To"),
		Status("Status"),
		Result("Result"),
		Stacktrace("Stacktrace"),
		ReplyTo("ReplyTo"),
		PersistEmail("PersistEmail"),
		TestMessage_EmailSettings("EmailTemplate.TestMessage_EmailSettings"),
		TestMessage_ModuleSetup("EmailTemplate.TestMessage_ModuleSetup");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestMessage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testMessageMendixObject)
	{
		if (testMessageMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, testMessageMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testMessageMendixObject = testMessageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TestMessage.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emailtemplate.proxies.TestMessage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emailtemplate.proxies.TestMessage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static emailtemplate.proxies.TestMessage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emailtemplate.proxies.TestMessage(context, mendixObject);
	}

	public static emailtemplate.proxies.TestMessage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emailtemplate.proxies.TestMessage.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of From
	 */
	public final java.lang.String getFrom()
	{
		return getFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of From
	 */
	public final java.lang.String getFrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.From.toString());
	}

	/**
	 * Set value of From
	 * @param from
	 */
	public final void setFrom(java.lang.String from)
	{
		setFrom(getContext(), from);
	}

	/**
	 * Set value of From
	 * @param context
	 * @param from
	 */
	public final void setFrom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String from)
	{
		getMendixObject().setValue(context, MemberNames.From.toString(), from);
	}

	/**
	 * @return value of To
	 */
	public final java.lang.String getTo()
	{
		return getTo(getContext());
	}

	/**
	 * @param context
	 * @return value of To
	 */
	public final java.lang.String getTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.To.toString());
	}

	/**
	 * Set value of To
	 * @param to
	 */
	public final void setTo(java.lang.String to)
	{
		setTo(getContext(), to);
	}

	/**
	 * Set value of To
	 * @param context
	 * @param to
	 */
	public final void setTo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String to)
	{
		getMendixObject().setValue(context, MemberNames.To.toString(), to);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final emailtemplate.proxies.Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final emailtemplate.proxies.Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return emailtemplate.proxies.Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(emailtemplate.proxies.Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, emailtemplate.proxies.Status status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of Result
	 */
	public final java.lang.String getResult()
	{
		return getResult(getContext());
	}

	/**
	 * @param context
	 * @return value of Result
	 */
	public final java.lang.String getResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Result.toString());
	}

	/**
	 * Set value of Result
	 * @param result
	 */
	public final void setResult(java.lang.String result)
	{
		setResult(getContext(), result);
	}

	/**
	 * Set value of Result
	 * @param context
	 * @param result
	 */
	public final void setResult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String result)
	{
		getMendixObject().setValue(context, MemberNames.Result.toString(), result);
	}

	/**
	 * @return value of Stacktrace
	 */
	public final java.lang.String getStacktrace()
	{
		return getStacktrace(getContext());
	}

	/**
	 * @param context
	 * @return value of Stacktrace
	 */
	public final java.lang.String getStacktrace(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Stacktrace.toString());
	}

	/**
	 * Set value of Stacktrace
	 * @param stacktrace
	 */
	public final void setStacktrace(java.lang.String stacktrace)
	{
		setStacktrace(getContext(), stacktrace);
	}

	/**
	 * Set value of Stacktrace
	 * @param context
	 * @param stacktrace
	 */
	public final void setStacktrace(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stacktrace)
	{
		getMendixObject().setValue(context, MemberNames.Stacktrace.toString(), stacktrace);
	}

	/**
	 * @return value of ReplyTo
	 */
	public final java.lang.String getReplyTo()
	{
		return getReplyTo(getContext());
	}

	/**
	 * @param context
	 * @return value of ReplyTo
	 */
	public final java.lang.String getReplyTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReplyTo.toString());
	}

	/**
	 * Set value of ReplyTo
	 * @param replyto
	 */
	public final void setReplyTo(java.lang.String replyto)
	{
		setReplyTo(getContext(), replyto);
	}

	/**
	 * Set value of ReplyTo
	 * @param context
	 * @param replyto
	 */
	public final void setReplyTo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String replyto)
	{
		getMendixObject().setValue(context, MemberNames.ReplyTo.toString(), replyto);
	}

	/**
	 * @return value of PersistEmail
	 */
	public final java.lang.Boolean getPersistEmail()
	{
		return getPersistEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of PersistEmail
	 */
	public final java.lang.Boolean getPersistEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PersistEmail.toString());
	}

	/**
	 * Set value of PersistEmail
	 * @param persistemail
	 */
	public final void setPersistEmail(java.lang.Boolean persistemail)
	{
		setPersistEmail(getContext(), persistemail);
	}

	/**
	 * Set value of PersistEmail
	 * @param context
	 * @param persistemail
	 */
	public final void setPersistEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean persistemail)
	{
		getMendixObject().setValue(context, MemberNames.PersistEmail.toString(), persistemail);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TestMessage_EmailSettings
	 */
	public final emailtemplate.proxies.EmailSettings getTestMessage_EmailSettings() throws com.mendix.core.CoreException
	{
		return getTestMessage_EmailSettings(getContext());
	}

	/**
	 * @param context
	 * @return value of TestMessage_EmailSettings
	 * @throws com.mendix.core.CoreException
	 */
	public final emailtemplate.proxies.EmailSettings getTestMessage_EmailSettings(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emailtemplate.proxies.EmailSettings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestMessage_EmailSettings.toString());
		if (identifier != null) {
			result = emailtemplate.proxies.EmailSettings.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TestMessage_EmailSettings
	 * @param testmessage_emailsettings
	 */
	public final void setTestMessage_EmailSettings(emailtemplate.proxies.EmailSettings testmessage_emailsettings)
	{
		setTestMessage_EmailSettings(getContext(), testmessage_emailsettings);
	}

	/**
	 * Set value of TestMessage_EmailSettings
	 * @param context
	 * @param testmessage_emailsettings
	 */
	public final void setTestMessage_EmailSettings(com.mendix.systemwideinterfaces.core.IContext context, emailtemplate.proxies.EmailSettings testmessage_emailsettings)
	{
		if (testmessage_emailsettings == null) {
			getMendixObject().setValue(context, MemberNames.TestMessage_EmailSettings.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TestMessage_EmailSettings.toString(), testmessage_emailsettings.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TestMessage_ModuleSetup
	 */
	public final emailtemplate.proxies.ModuleSetup getTestMessage_ModuleSetup() throws com.mendix.core.CoreException
	{
		return getTestMessage_ModuleSetup(getContext());
	}

	/**
	 * @param context
	 * @return value of TestMessage_ModuleSetup
	 * @throws com.mendix.core.CoreException
	 */
	public final emailtemplate.proxies.ModuleSetup getTestMessage_ModuleSetup(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emailtemplate.proxies.ModuleSetup result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestMessage_ModuleSetup.toString());
		if (identifier != null) {
			result = emailtemplate.proxies.ModuleSetup.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TestMessage_ModuleSetup
	 * @param testmessage_modulesetup
	 */
	public final void setTestMessage_ModuleSetup(emailtemplate.proxies.ModuleSetup testmessage_modulesetup)
	{
		setTestMessage_ModuleSetup(getContext(), testmessage_modulesetup);
	}

	/**
	 * Set value of TestMessage_ModuleSetup
	 * @param context
	 * @param testmessage_modulesetup
	 */
	public final void setTestMessage_ModuleSetup(com.mendix.systemwideinterfaces.core.IContext context, emailtemplate.proxies.ModuleSetup testmessage_modulesetup)
	{
		if (testmessage_modulesetup == null) {
			getMendixObject().setValue(context, MemberNames.TestMessage_ModuleSetup.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TestMessage_ModuleSetup.toString(), testmessage_modulesetup.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testMessageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emailtemplate.proxies.TestMessage that = (emailtemplate.proxies.TestMessage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
